# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e0264ecb80e7a6c22dc0176a061ebdb396c57ebd4cebd2fb49bc6d63593eb1da1ec26492549c0374bf8106ed0601d82910fa6dcc88d239142b8d736fdfb322

test:
  secret_key_base: 9f4a457f42ac6ad86fc26c85d6441ff92a9d0f8a8a3bcb45ca2907762a56179f0b47701147e46b9d657ccdccb893b4d4365ae6cefc1078654832bec837515150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
